Recipe.destroy_all()
User.destroy_all()
Ingredient.destroy_all()

Ingredient.create({ name: "Aduki Bean"})
Ingredient.create({ name: "Agar-Agar"})
Ingredient.create({ name: "Agave Syrup"})
Ingredient.create({ name: "Albarino"})
Ingredient.create({ name: "Almond"})
Ingredient.create({ name: "Amaranth"})
Ingredient.create({ name: "Anchovy"})
Ingredient.create({ name: "Angelica"})
Ingredient.create({ name: "Apple"})
Ingredient.create({ name: "Apricot"})
Ingredient.create({ name: "Arborio rice"})
Ingredient.create({ name: "Asafoetida"})
Ingredient.create({ name: "Avocado"})
Ingredient.create({ name: "Asparagus"})
Ingredient.create({ name: "Aubergine"})
Ingredient.create({ name: "Bacon"})
Ingredient.create({ name: "Baking Powder"})
Ingredient.create({ name: "Balsamic Vinegar"})
Ingredient.create({ name: "Banana"})
Ingredient.create({ name: "Barbera"})
Ingredient.create({ name: "Barley"})
Ingredient.create({ name: "Basil"})
Ingredient.create({ name: "Bavette"})
Ingredient.create({ name: "Beef"})
Ingredient.create({ name: "Beetroot"})
Ingredient.create({ name: "Bicarbonate of Soda"})
Ingredient.create({ name: "Blackberry"})
Ingredient.create({ name: "Blackcurrant"})
Ingredient.create({ name: "Blueberry"})
Ingredient.create({ name: "Bramley Apple"})
Ingredient.create({ name: "Broad Bean"})
Ingredient.create({ name: "Brandy"})
Ingredient.create({ name: "Broccoli"})
Ingredient.create({ name: "Butter"})
Ingredient.create({ name: "Brussels Sprouts"})
Ingredient.create({ name: "Buckwheat"})
Ingredient.create({ name: "Cabbage"})
Ingredient.create({ name: "Cabernet Sauvignon"})
Ingredient.create({ name: "Cannellini bean"})
Ingredient.create({ name: "Capers"})
Ingredient.create({ name: "Caramel"})
Ingredient.create({ name: "Carrot"})
Ingredient.create({ name:"Cashew"})
Ingredient.create({ name:"Cauliflower"})
Ingredient.create({ name: "Caviar"})
Ingredient.create({ name: "Cavolo Nero"})
Ingredient.create({ name: "Celery"})
Ingredient.create({ name: "Champagne"})
Ingredient.create({ name: "Chardonnay"})
Ingredient.create({ name: "Chataubriand"})
Ingredient.create({ name: "Cheddar"})
Ingredient.create({ name: "Chenin Blanc"})
Ingredient.create({ name: "Cherry"})
Ingredient.create({ name: "Chervil"})
Ingredient.create({ name: "Chestnut"})
Ingredient.create({ name: "Chia"})
Ingredient.create({ name: "Chianti"})
Ingredient.create({ name: "Chicken"})
Ingredient.create({ name: "Chicory"})
Ingredient.create({ name: "Chilli"})
Ingredient.create({ name: "Chorizo"})
Ingredient.create({ name: "Cider"})
Ingredient.create({ name: "Cinnamon"})
Ingredient.create({ name: "Clementine"})
Ingredient.create({ name: "Clove"})
Ingredient.create({ name: "Cockles"})
Ingredient.create({ name: "Coconut"})
Ingredient.create({ name: "Cod"})
Ingredient.create({ name: "Colombard"})
Ingredient.create({ name: "Corriander Seed"})
Ingredient.create({ name: "Courgette"})
Ingredient.create({ name: "Courgette Flower"})
Ingredient.create({ name: "Couscous"})
Ingredient.create({ name: "Crab"})
Ingredient.create({ name: "Cranberry"})
Ingredient.create({ name: "Cognac"})
Ingredient.create({ name: "Cream"})
Ingredient.create({ name: "Crepe"})
Ingredient.create({ name: "Cumin"})
Ingredient.create({ name: "Damson"})
Ingredient.create({ name: "Date"})
Ingredient.create({ name: "Duck"})
Ingredient.create({ name: "Egg"})
Ingredient.create({ name: "Fennel Bulb"})
Ingredient.create({ name: "Fennel Leaf"})
Ingredient.create({ name: "Fennel Seed"})
Ingredient.create({ name: "Fenugreek"})
Ingredient.create({ name: "Fenugreek Seed"})
Ingredient.create({ name: "Feta"})
Ingredient.create({ name: "Fig"})
Ingredient.create({ name: "Fish Sauce"})
Ingredient.create({ name: "Fleur de sel"})
Ingredient.create({ name: "Plain Flour"})
Ingredient.create({ name: "Self Raising Flour"})
Ingredient.create({ name: "Wholemeal Flour"})
Ingredient.create({ name: "Strong Flour"})
Ingredient.create({ name: "Rice FLour"})
Ingredient.create({ name: "Cornmeal"})
Ingredient.create({ name: "Ground Almonds"})
Ingredient.create({ name: "Foie Gras"})
Ingredient.create({ name: "Frangipane"})
Ingredient.create({ name: "Frisee"})
Ingredient.create({ name: "Freekeh"})
Ingredient.create({ name: "Gamay"})
Ingredient.create({ name: "Garam Masala"})
Ingredient.create({ name: "Garlic"})
Ingredient.create({ name: "Gelatine"})
Ingredient.create({ name: "Ghee"})
Ingredient.create({ name: "Gin"})
Ingredient.create({ name: "Ginger"})
Ingredient.create({ name: "Globe Artichoke"})
Ingredient.create({ name: "Gochujang"})
Ingredient.create({ name: "Gochugaru"})
Ingredient.create({ name: "Goji Berry"})
Ingredient.create({ name: "Goose"})
Ingredient.create({ name: "Gooseberry"})
Ingredient.create({ name: "Gorgonzola"})
Ingredient.create({ name: "Grapefruit"})
Ingredient.create({ name: "Gravy"})
Ingredient.create({ name: "Green Tea"})
Ingredient.create({ name: "Grenache"})
Ingredient.create({ name: "Grouse"})
Ingredient.create({ name: "Noble Grape"})
Ingredient.create({ name: "Gruyere"})
Ingredient.create({ name: "Guiney Fowl"})
Ingredient.create({ name: "Gurnard"})
Ingredient.create({ name: "Haddock"})
Ingredient.create({ name: "Haggis"})
Ingredient.create({ name: "Halibut"})
Ingredient.create({ name: "Halloumi"})
Ingredient.create({ name: "Harissa"})
Ingredient.create({ name: "Hazelnut"})
Ingredient.create({ name: "Herring"})
Ingredient.create({ name: "Honey"})
Ingredient.create({ name: "Honeycomb"})
Ingredient.create({ name: "Ink, Squid"})
Ingredient.create({ name: "Jalapeno"})
Ingredient.create({ name: "Jerusalem Artichoke"})
Ingredient.create({ name: "Kale"})
Ingredient.create({ name: "Kamut"})
Ingredient.create({ name: "Ketjap Manis"})
Ingredient.create({ name: "Ketcap Manis"})
Ingredient.create({ name: "Kimchi"})
Ingredient.create({ name: "Kipper"})
Ingredient.create({ name: "Kirsch"})
Ingredient.create({ name: "Kiwi Fruit"})
Ingredient.create({ name: "Kumquat"})
Ingredient.create({ name: "Kohlrabi"})
Ingredient.create({ name: "Lamb"})
Ingredient.create({ name: "Lambs Lettuce"})
Ingredient.create({ name: "Leek"})
Ingredient.create({ name: "Lemon"})
Ingredient.create({ name: "Lemon Grass"})
Ingredient.create({ name: "Lentils"})
Ingredient.create({ name: "Lettuce"})
Ingredient.create({ name: "Lime"})
Ingredient.create({ name: "Lobster"})
Ingredient.create({ name: "Lime Leaf"})
Ingredient.create({ name: "Linseed"})
Ingredient.create({ name: "Flaxseed"})
Ingredient.create({ name: "Maca"})
Ingredient.create({ name: "Mackrel"})
Ingredient.create({ name: "Malbec"})
Ingredient.create({ name: "Manchego"})
Ingredient.create({ name: "Marrow"})
Ingredient.create({ name: "Marzipan"})
Ingredient.create({ name: "Merlot"})
Ingredient.create({ name: "Milk"})
Ingredient.create({ name: "Millet"})
Ingredient.create({ name: "Mint"})
Ingredient.create({ name: "Miso"})
Ingredient.create({ name: "Molasses"})
Ingredient.create({ name: "Moringa"})
Ingredient.create({ name: "Muscat"})
Ingredient.create({ name: "Mushroom"})
Ingredient.create({ name: "Mustard"})
Ingredient.create({ name: "Mussels"})
Ingredient.create({ name: "Nduja"})
Ingredient.create({ name: "Nebbiolo"})
Ingredient.create({ name: "Nectarine"})
Ingredient.create({ name: "Negroamaro"})
Ingredient.create({ name: "Nigella seed"})
Ingredient.create({ name: "New Potatoes"})
Ingredient.create({ name: "Okra"})
Ingredient.create({ name: "Olive"})
Ingredient.create({ name: "Olive Oil"})
Ingredient.create({ name: "Onglet"})
Ingredient.create({ name: "Oyster"})
Ingredient.create({ name: "Yellow Onion"})
Ingredient.create({ name: "Red Onion"})
Ingredient.create({ name: "Spring Onion"})
Ingredient.create({ name: "Shallots"})
Ingredient.create({ name: "Orange"})
Ingredient.create({ name: "Oregano"})
Ingredient.create({ name: "Pak Choi"})
Ingredient.create({ name: "Pancetta"})
Ingredient.create({ name: "Papaya"})
Ingredient.create({ name: "Papillote"})
Ingredient.create({ name: "Paprika"})
Ingredient.create({ name: "Parmesan"})
Ingredient.create({ name: "Parsley"})
Ingredient.create({ name: "Parsnip"})
Ingredient.create({ name: "Peach"})
Ingredient.create({ name: "Pear"})
Ingredient.create({ name: "Peas"})
Ingredient.create({ name: "Pecan"})
Ingredient.create({ name: "Pepper"})
Ingredient.create({ name: "Persimmon"})
Ingredient.create({ name: "Pesto"})
Ingredient.create({ name: "Pilchard"})
Ingredient.create({ name: "Pineapple"})
Ingredient.create({ name: "Pinot Gris"})
Ingredient.create({ name: "Pinot Noir"})
Ingredient.create({ name: "Pinotage"})
Ingredient.create({ name: "Piri-piri"})
Ingredient.create({ name: "Plum"})
Ingredient.create({ name: "Pomegranate"})
Ingredient.create({ name: "Pork"})
Ingredient.create({ name: "Potato"})
Ingredient.create({ name: "Prawn"})
Ingredient.create({ name: "Purple Sprouting Broccoli"})
Ingredient.create({ name: "Prosciutto"})
Ingredient.create({ name: "Prosecco"})
Ingredient.create({ name: "Pumpkin"})
Ingredient.create({ name: "Quinoa"})
Ingredient.create({ name: "Quail"})
Ingredient.create({ name: "Quark"})
Ingredient.create({ name: "Quince"})
Ingredient.create({ name: "Radicchio"})
Ingredient.create({ name: "Raddish"})
Ingredient.create({ name: "Rapeseed Oil"})
Ingredient.create({ name: "Raspberry"})
Ingredient.create({ name: "Redcurrant"})
Ingredient.create({ name: "Rhubarb"})
Ingredient.create({ name: "Rib-eye Steak"})
Ingredient.create({ name: "Rice"})
Ingredient.create({ name: "Rice Syrup"})
Ingredient.create({ name: "Ricotta"})
Ingredient.create({ name: "riesling"})
Ingredient.create({ name: "Risotto rice"})
Ingredient.create({ name: "Runner Bean"})
Ingredient.create({ name: "Rocket"})
Ingredient.create({ name: "Rosemary"})
Ingredient.create({ name: "Saffron"})
Ingredient.create({ name: "Sage"})
Ingredient.create({ name: "Salami"})
Ingredient.create({ name: "Salmon"})
Ingredient.create({ name: "Salsify"})
Ingredient.create({ name: "Saurkraut"})
Ingredient.create({ name: "Sauvignon Blanc"})
Ingredient.create({ name: "Scallop"})
Ingredient.create({ name: "Samphire"})
Ingredient.create({ name: "Sangiovese"})
Ingredient.create({ name: "Sardine"})
Ingredient.create({ name: "Semillon"})
Ingredient.create({ name: "Semolina"})
Ingredient.create({ name: "Shallot"})
Ingredient.create({ name: "Shichimi Togarashi"})
Ingredient.create({ name: "Sirloin Steak"})
Ingredient.create({ name: "Smoked Anchovies"})
Ingredient.create({ name: "Smoked Salt"})
Ingredient.create({ name: "Sorrel"})
Ingredient.create({ name: "Soy Sauce"})
Ingredient.create({ name: "Soya Beans"})
Ingredient.create({ name: "Spelt"})
Ingredient.create({ name: "Spinach"})
Ingredient.create({ name: "Spirulina"})
Ingredient.create({ name: "Spring Greens"})
Ingredient.create({ name: "Spring Lamb"})
Ingredient.create({ name: "Squid"})
Ingredient.create({ name: "Sriracha sauce"})
Ingredient.create({ name: "Star anise"})
Ingredient.create({ name: "Steak"})
Ingredient.create({ name: "Stilton"})
Ingredient.create({ name: "Strawberry"})
Ingredient.create({ name: "Sugar"})
Ingredient.create({ name: "Sumac"})
Ingredient.create({ name: "Sunflower Oil"})
Ingredient.create({ name: "Sushi"})
Ingredient.create({ name: "Swede"})
Ingredient.create({ name: "Sweet Potato"})
Ingredient.create({ name: "Sweetcorn"})
Ingredient.create({ name: "Swiss Chard"})
Ingredient.create({ name: "Shiraz"})
Ingredient.create({ name: "Syrah"})
Ingredient.create({ name: "Tahini"})
Ingredient.create({ name: "Tamari"})
Ingredient.create({ name: "Tamarind"})
Ingredient.create({ name: "Tannin"})
Ingredient.create({ name: "Tarragon"})
Ingredient.create({ name: "Teff"})
Ingredient.create({ name: "Temparanillo"})
Ingredient.create({ name: "Thai Red Curry Paste"})
Ingredient.create({ name: "Thai Green Curry Paste"})
Ingredient.create({ name: "Thai Curry Paste"})
Ingredient.create({ name: "Tomato"})
Ingredient.create({ name: "Tortilla"})
Ingredient.create({ name: "Trout"})
Ingredient.create({ name: "Truffle"})
Ingredient.create({ name: "Truffle Oil"})
Ingredient.create({ name: "Tuna"})
Ingredient.create({ name: "Turbot"})
Ingredient.create({ name: "Turnip"})
Ingredient.create({ name: "Turkey"})
Ingredient.create({ name: "Turmeric"})
Ingredient.create({ name: "Udon"})
Ingredient.create({ name: "Vacherin"})
Ingredient.create({ name: "Vanilla"})
Ingredient.create({ name: "Venison"})
Ingredient.create({ name: "Vodka"})
Ingredient.create({ name: "Viognier"})
Ingredient.create({ name: "Walnut"})
Ingredient.create({ name: "Wasabi"})
Ingredient.create({ name: "Watermelon"})
Ingredient.create({ name: "Wholemeal"})
Ingredient.create({ name: "Whisky"})
Ingredient.create({ name: "Whiting"})
Ingredient.create({ name: "Xylitol"})
Ingredient.create({ name: "Yuzu"})
Ingredient.create({ name: "Yeast"})
Ingredient.create({ name: "Yogurt"})
Ingredient.create({ name: "Zinfandel"})


r1 = Recipe.create({
  name: "Spicy Chorizo Nachos",
  ingredients: "Red_Onion,1 Clove_of_Garlic,1 Tomatoes,2 Green_Pepper,1 Red_Pepper,1 Red_Chilli,1 Fresh_Parsley,1Bunch Ground_Cumin,1tsp Ground_Paprika,1tsp Salt,1tsp Chorizo,225g Iberico_Ham,50g Lightly_Salted_Corn_Chips,200g Manchego_Cheese,250g Aioli,4tbsp Fresh_Coriander,1handful Fresh_Chilli,1",
  method: "Step 1
MAKE THE SALSA
Peel and chunk up the onion and garlic, quarter the tomatoes, then deseed and roughly chop the peppers and chilli. Blitz all of them in a food processor with the parsley, spices and salt to a coarse paste.

Step 2
CHORIZO TIME
Heat a saucepan or large frying pan over a pretty high heat then add a drizzle of olive oil and the sliced chorizo. Fry for 2-3 minutes to release the oils from the chorizo, then dump the blitzed paste into the pan. Simmer for 5 minutes so that much of the water content evaporates.

Step 3
STACK IT UP
Pile the corn chips onto a heatproof bowl, layering some of your spicy chorizo salsa in between. Grate over stacks of the cheese, then place under a grill to melt the cheese and brown parts of it. Drape slices of the ham over he top, dot with aioli and garnish with more fresh chilli and the fresh coriander. Eat immediately with ice cold beer!",
  image: "example.png",
  style: "Mexican Spanish",
  course: "Sharing Starter Main"
  })

r2 = Recipe.create({
  name: "Boiled Potato",
  ingredients: "Potato,1 water,enough",
  method: "Boil potato, Eat potato"
  })

user1 = User.create({
  email: "lewis@email.com",
  password: "password",
  password_confirmation: "password"
  })

user2 = User.create({
  email: "steph@email.com",
  password: "password",
  password_confirmation: "password"
  })

FavouriteRecipe.create({
  recipe: r2,
  user: user1
  })

FavouriteRecipe.create({
  recipe: r2,
  user: user2
  })


FavouriteRecipe.create({
  recipe: r1,
  user: user2
  })